nelmio_api_doc:
    documentation:
        info:
            title: Symfony api example
            version: 1.0.0
        
        security:
            - Bearer: []

        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
                    description: 'Enter JWT token'

            parameters:
                Authorization:
                    name: Authorization
                    in: header
                    description: 'Bearer {token}'
                    required: true
                    schema:
                        type: string

        paths:
            /api/auth:
                post:
                    tags:
                        - Auth
                    security: [] # This removes auth requirement for login endpoint
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    properties:
                                        username:
                                            type: string
                                        password:
                                            type: string
                    responses:
                        200:
                            description: User login
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string

    areas: # to filter documented areas
        path_patterns: # an array of regexps
            - ^/api(?!/doc$)
