nelmio_api_doc:
    documentation:
        info:
            title: Symfony api example
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns: # an array of regexps
            - ^/api(?!/doc$)
