nelmio_api_doc:
    documentation:
        info:
            title: Symfony api example
            version: 1.0.0

        paths:
            /api/auth:
                post:
                    tags:
                        - Auth
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    properties:
                                        username:
                                            type: string
                                        password:
                                            type: string
                    responses:
                        200:
                            description: User login
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string

        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT


    areas: # to filter documented areas
        path_patterns: # an array of regexps
            - ^/api(?!/doc$)
