version: '3.3'

services:
    nginx_symfony_api:
        build:
            context: nginx
        volumes:
            - ${APP_PATH}:/var/www
        depends_on:
            - php_symfony_api
        ports:
            - 80:80
        networks:
            symfony_api:
                ipv4_address: 10.8.0.2

    php_symfony_api:
        container_name: php_symfony_api
        build:
            context: php8-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        networks:
            symfony_api:
                ipv4_address: 10.8.0.3
        volumes:
            - ${APP_PATH}:/var/www
        links:
            - mysql_symfony_api
        environment:
            XDEBUG_CONFIG: remote_host=${IP_ADDRESS}

    mysql_symfony_api:
        container_name: mysql_symfony_api
        image: mysql:8
        volumes:
            - mysql_symfony_api_data_container:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - 3306:3306
        networks:
            symfony_api:
                ipv4_address: 10.8.0.4

    adminer_symfony_api:
        container_name: adminer_symfony_api
        image: adminer
        ports:
            - 8080:8080

networks:
    symfony_api:
        driver: bridge
        ipam:
            config:
            - subnet: 10.8.0.0/16

volumes:
    mysql_symfony_api_data_container:
