services:
    nginx_symfony_api:
        build:
            context: nginx
        volumes:
            - ${APP_PATH}:/app
        depends_on:
            - php_symfony_api
        ports:
            - 80:80

    php_symfony_api:
        container_name: php_symfony_api
        build:
            context: php8-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${APP_PATH}:/app
        links:
            - mysql_symfony_api
        environment:
            PHP_IDE_CONFIG: serverName=localhost
        extra_hosts:
            - "host.docker.internal:host-gateway"

    mysql_symfony_api:
        container_name: mysql_symfony_api
        image: mysql:8
        volumes:
            - mysql_symfony_api_data_container:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - 3306:3306

volumes:
    mysql_symfony_api_data_container:
