app.swagger_ui:
  path: /
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
  path: /swagger/doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }

api_login_check:
  path: /api/login_check
